;; caixa.lisp — generated by tatara-rust-caixa (tatara-rust-ast).
;;
;; Consumed by `pleme-doc-gen` for the SDLC pipeline (Cargo.toml +
;; .pleme-io-release.toml + CI shims + nix module trio + flake.nix).
;; Re-emit with `pleme-doc-gen caixa --source caixa.lisp --out .`.

(defcaixa pleme-variantcount-derive
  :kind         "Biblioteca"
  :ecosystem    "rust-single-crate"

  :package      { :name        "pleme-variantcount-derive"
                  :version     "0.1.0"
                  :license     "MIT"
                  :description "Generated by tatara-rust-ast."
                  :repository  "https://github.com/pleme-io/pleme-variantcount-derive"
                  :homepage    "https://github.com/pleme-io/pleme-variantcount-derive"
                  :categories  [ "development-tools::procedural-macro-helpers" ]
                  :keywords    [ "tatara" "macro" "derive" "generated" ] }

  :ci-config    { :bump    { :default-type "patch" }
                  :publish { :no-verify false } }

  :workflows    [ :auto-release ]
  :stacks       [ ]
  :depends-on   [ ]
  :exposes      [ :rust-crate ]
  :publish-to-git true)
